-- ============================================
-- BridgeFlow Seed Data
-- Run this AFTER supabase-schema.sql
-- ============================================

-- Site Config
INSERT INTO site_config (name, tagline, description, url, email, location, copyright, logo, nav_links, footer_links, social_links) VALUES (
  'BridgeFlow',
  'AI-Powered Automation Agency',
  'BridgeFlow helps B2B businesses streamline workflows with AI-powered automation services and SaaS tools, built for global scale.',
  'https://www.bridgeflow.agency',
  'hello@bridgeflow.agency',
  'Remote-first, Global',
  '© 2026 BridgeFlow. All rights reserved.',
  '/images/logo.png',
  '[{"href":"/","label":"Home"},{"href":"/services","label":"Services"},{"href":"/about","label":"About"},{"href":"/case-studies","label":"Case Studies"},{"href":"/blog","label":"Blog"},{"href":"/contact","label":"Contact"}]'::jsonb,
  '{"company":[{"label":"About","href":"/about"},{"label":"Case Studies","href":"/case-studies"},{"label":"Blog","href":"/blog"},{"label":"Careers","href":"#"}],"services":[{"label":"n8n Automation","href":"/services"},{"label":"AI Integration","href":"/services"},{"label":"SaaS Tools","href":"/services"},{"label":"Consulting","href":"/services"}],"resources":[{"label":"Documentation","href":"#"},{"label":"API Reference","href":"#"},{"label":"Privacy Policy","href":"#"},{"label":"Terms of Service","href":"#"}]}'::jsonb,
  '[{"platform":"Twitter","href":"#"},{"platform":"LinkedIn","href":"#"},{"platform":"GitHub","href":"#"}]'::jsonb
);

-- Home Content
INSERT INTO home_content (hero, stats, services_overview, process_steps, testimonials, cta) VALUES (
  '{"badge":"AI-Powered Automation Agency","title":"Automate your","titleLine2":"Business with","highlight":"AI","description":"BridgeFlow helps B2B businesses streamline workflows with AI-powered automation services and SaaS tools, built for global scale.","ctaPrimary":{"text":"Get Started","href":"/contact"},"ctaSecondary":{"text":"View Services","href":"/services"}}'::jsonb,
  '[{"end":150,"suffix":"+","label":"Workflows Built"},{"end":40,"suffix":"+","label":"Happy Clients"},{"end":98,"suffix":"%","label":"Uptime SLA"},{"end":10,"suffix":"x","label":"Avg. ROI"}]'::jsonb,
  '[{"icon":"Zap","title":"n8n Automation","description":"Custom workflow builds using n8n for any business process. Automate lead gen, onboarding, reporting, and more.","href":"/services"},{"icon":"Bot","title":"AI Integration","description":"Connect your tools with AI to work smarter. GPT, Claude, and custom models integrated into your workflows.","href":"/services"},{"icon":"Boxes","title":"SaaS Tools","description":"Access our growing suite of automation SaaS products built for specific business verticals.","href":"/services"}]'::jsonb,
  '[{"step":"01","title":"Consult","description":"We analyze your business processes and identify automation opportunities that deliver the highest ROI."},{"step":"02","title":"Build","description":"Our engineers architect and deploy custom automation workflows tailored to your exact needs."},{"step":"03","title":"Scale","description":"We monitor, optimize, and scale your automations as your business grows — zero downtime guaranteed."}]'::jsonb,
  '[{"quote":"BridgeFlow automated our entire lead pipeline. We went from 4 hours of manual work daily to completely hands-off in 2 weeks.","author":"Sarah Chen","role":"VP Operations, TechScale Inc.","rating":5},{"quote":"The ROI was immediate. Our onboarding time dropped by 80% and client satisfaction scores went through the roof.","author":"Marcus Rivera","role":"CEO, GrowthBase","rating":5},{"quote":"Their AI integration with our CRM was seamless. The team is incredibly responsive and the results speak for themselves.","author":"Aisha Patel","role":"Head of Sales, Nexus Digital","rating":5}]'::jsonb,
  '{"title":"Ready to","highlight":"Automate?","description":"Let''s talk about your business and build your first automation together — no commitments.","ctaPrimary":{"text":"Start a Conversation","href":"/contact"},"ctaSecondary":{"text":"hello@bridgeflow.agency","href":"mailto:hello@bridgeflow.agency"}}'::jsonb
);

-- Services
INSERT INTO services (title, icon, description, features, color, sort_order) VALUES
('n8n Workflow Automation', 'Zap', 'We design and deploy custom n8n workflows that automate your most time-consuming business processes. From lead capture to invoice generation, we handle it all.', '["Custom workflow design & deployment","Multi-step automation sequences","CRM, email, and database integrations","Error handling & retry logic","Real-time monitoring dashboards","Scheduled & trigger-based flows"]'::jsonb, 'from-amber-500 to-gold-400', 0),
('AI Integration', 'Bot', 'Supercharge your workflows with AI. We integrate GPT, Claude, and custom models directly into your business processes for intelligent automation.', '["GPT-4 & Claude API integration","Custom AI model training & fine-tuning","Natural language processing pipelines","AI-powered content generation","Intelligent data extraction & analysis","Chatbot & virtual assistant setup"]'::jsonb, 'from-blue-500 to-cyan-400', 1),
('SaaS Tools', 'Boxes', 'Access our growing suite of pre-built SaaS products designed to solve specific automation challenges out of the box.', '["Ready-to-deploy automation tools","White-label solutions available","API-first architecture","Multi-tenant infrastructure","Custom branding & configuration","99.9% uptime guarantee"]'::jsonb, 'from-purple-500 to-pink-400', 2),
('Consulting & Strategy', 'MessageSquare', 'Not sure where to start? Our automation consultants will audit your processes, identify opportunities, and build a roadmap for transformation.', '["Process audit & mapping","ROI analysis & projections","Technology stack recommendations","Implementation roadmap","Team training & onboarding","Ongoing optimization support"]'::jsonb, 'from-emerald-500 to-teal-400', 3);

-- Benefits
INSERT INTO benefits (icon, title, description, sort_order) VALUES
('Clock', 'Save 20+ hours/week', 'Eliminate repetitive manual tasks', 0),
('BarChart3', '10x Average ROI', 'Proven return on investment', 1),
('Shield', 'Enterprise Security', 'SOC 2 compliant infrastructure', 2),
('Globe', 'Global Scale', 'Deploy automations worldwide', 3),
('Users', 'Dedicated Support', '24/7 expert assistance', 4),
('Settings', 'Custom Solutions', 'Tailored to your exact needs', 5);

-- Team Members
INSERT INTO team_members (name, role, initials, sort_order) VALUES
('Alex Moreau', 'CEO & Founder', 'AM', 0),
('Priya Sharma', 'Head of Engineering', 'PS', 1),
('James Okonkwo', 'AI Solutions Architect', 'JO', 2),
('Elena Vasquez', 'Client Success Lead', 'EV', 3);

-- Company Values
INSERT INTO company_values (icon, title, description, sort_order) VALUES
('Target', 'Results-Driven', 'Every automation we build is measured by its impact on your bottom line.', 0),
('Rocket', 'Speed First', 'We ship fast. Most automations are live within 1-2 weeks of kickoff.', 1),
('Heart', 'Client Obsessed', 'Your success is our success. We maintain a 98% client retention rate.', 2),
('Lightbulb', 'AI-Native', 'We don''t just use AI — we breathe it. Every solution leverages cutting-edge AI.', 3);

-- Milestones
INSERT INTO milestones (year, title, description, sort_order) VALUES
('2024', 'Founded', 'BridgeFlow launched with a mission to democratize automation for B2B businesses.', 0),
('2024', 'First 10 Clients', 'Delivered 50+ automations across SaaS, e-commerce, and consulting.', 1),
('2025', 'SaaS Launch', 'Released our first suite of pre-built automation tools for specific verticals.', 2),
('2025', 'Global Expansion', 'Expanded to serve clients across 15+ countries with a fully remote team.', 3),
('2026', 'AI-First Pivot', 'Deep integration of GPT-4, Claude, and custom AI models into every workflow.', 4);

-- Tech Stack
INSERT INTO tech_stack (icon, name, description, sort_order) VALUES
('Workflow', 'n8n', 'Workflow Engine', 0),
('Cpu', 'OpenAI', 'AI Models', 1),
('Code2', 'Next.js', 'Web Platform', 2),
('Database', 'PostgreSQL', 'Data Layer', 3),
('Globe', 'Vercel', 'Cloud Hosting', 4),
('Cpu', 'Claude AI', 'AI Assistant', 5);

-- Blog Posts
INSERT INTO blog_posts (slug, title, excerpt, content, category, read_time, featured, is_published, created_at) VALUES
('future-of-n8n-automation-2026', 'The Future of n8n Automation in 2026', 'Explore the latest trends in workflow automation and how n8n is evolving to handle increasingly complex business processes.', E'The automation landscape is evolving rapidly, and n8n continues to be at the forefront of workflow innovation. As we move through 2026, several key trends are reshaping how businesses approach automation.\n\nFirst, AI-native workflows are becoming the norm. Gone are the days of simple if-then rules — modern automations leverage GPT-4 and Claude for intelligent decision-making within workflow nodes.\n\nSecond, the rise of ''composable automation'' means businesses can mix and match pre-built workflow modules to create complex systems in hours, not weeks. BridgeFlow has been pioneering this approach with our modular workflow library.\n\nThird, real-time event-driven architectures are replacing scheduled batch processes. With webhooks and streaming APIs, automations now respond to business events as they happen, delivering instant results.\n\nThe future of n8n automation is intelligent, modular, and real-time. Businesses that embrace these trends today will have a significant competitive advantage tomorrow.', 'Automation', '5 min read', true, true, '2026-02-15T00:00:00Z'),
('ai-integration-beginners-guide', 'AI Integration: A Beginner''s Guide for B2B Companies', 'Everything you need to know about integrating AI into your business workflows — from choosing the right model to measuring ROI.', E'Integrating AI into your business doesn''t have to be overwhelming. This guide breaks down the process into manageable steps that any B2B company can follow.\n\nStep 1: Identify High-Impact Use Cases. Start by cataloging your most repetitive, time-consuming tasks. Lead qualification, data entry, report generation, and customer support are common first targets.\n\nStep 2: Choose Your AI Model. Not every task needs GPT-4. Simple classification might work with a lightweight model, while complex content generation benefits from larger models. Consider cost, speed, and accuracy.\n\nStep 3: Build the Integration Layer. Use tools like n8n to connect your AI model to your existing business tools. The key is creating a seamless flow where AI enhances — not replaces — human workflows.\n\nStep 4: Measure and Iterate. Track key metrics like time saved, accuracy, and ROI. Use these insights to refine your AI integration and expand to new use cases.', 'AI', '8 min read', true, true, '2026-02-10T00:00:00Z'),
('automate-lead-pipeline', 'How to Automate Your Entire Lead Pipeline in 7 Days', 'A step-by-step tutorial on building an automated lead capture, qualification, and follow-up system using n8n.', E'In this tutorial, we''ll walk through building a complete lead pipeline automation using n8n. By the end, you''ll have a system that captures leads, qualifies them with AI, and nurtures them automatically.\n\nDay 1-2: Set up your lead capture. Connect all your lead sources — web forms, LinkedIn, email — to a central n8n workflow using webhooks.\n\nDay 3-4: Build the qualification engine. Use GPT-4 to score leads based on firmographic data, engagement signals, and intent indicators.\n\nDay 5-6: Create the nurture sequences. Design automated email sequences that adapt based on lead behavior and scoring.\n\nDay 7: Test and launch. Run end-to-end tests with sample data, then go live and start monitoring results.', 'Tutorials', '12 min read', false, true, '2026-02-05T00:00:00Z'),
('saas-automation-trends', '5 SaaS Automation Trends Reshaping B2B', 'From AI-powered analytics to no-code integrations, these are the automation trends every B2B leader needs to watch.', E'The B2B SaaS landscape is undergoing a fundamental transformation driven by automation. Here are the five trends that matter most.\n\n1. AI-Powered Analytics: Tools are moving beyond dashboards to proactive, AI-driven insights that tell you what to do next.\n\n2. No-Code Integration Platforms: Connecting SaaS tools no longer requires developers. Platforms like n8n make it accessible to business users.\n\n3. Vertical-Specific Automation: Generic tools are giving way to industry-specific solutions built for healthcare, finance, and real estate.\n\n4. Revenue Operations Automation: Sales, marketing, and customer success are being unified through automated RevOps workflows.\n\n5. Composable Architecture: Businesses are building tech stacks from modular, interchangeable components rather than monolithic platforms.', 'Industry', '6 min read', false, true, '2026-01-28T00:00:00Z'),
('workflow-optimization-tips', '10 Workflow Optimization Tips That Save 20+ Hours/Week', 'Practical techniques our team uses to identify bottlenecks and automate repetitive tasks across any business.', E'After building 150+ workflows for clients, we''ve identified the most impactful optimization strategies. Here are our top 10.\n\n1. Map before you automate. Document every step of your current process before building workflows.\n\n2. Start with the 80/20 rule. Identify the 20% of tasks that consume 80% of your time.\n\n3. Use parallel execution. Run independent workflow branches simultaneously instead of sequentially.\n\n4. Implement smart error handling. Build retry logic and fallback paths for every critical node.\n\n5. Monitor proactively. Set up alerts for workflow failures before they impact your business.\n\n6. Cache frequently accessed data. Reduce API calls by storing commonly needed data locally.\n\n7. Use conditional routing. Skip unnecessary steps by routing data based on conditions.\n\n8. Batch process when possible. Group similar operations together to reduce overhead.\n\n9. Version your workflows. Keep backups of working configurations before making changes.\n\n10. Review and iterate monthly. Schedule regular optimization reviews to keep workflows efficient.', 'Automation', '7 min read', false, true, '2026-01-20T00:00:00Z'),
('gpt4-business-applications', 'GPT-4 in Business: Beyond the Hype', 'Real-world applications of GPT-4 in B2B — from automated report generation to intelligent customer support.', E'GPT-4 has moved beyond the hype cycle and into real business applications. Here''s how B2B companies are using it today.\n\nAutomated Report Generation: Companies are using GPT-4 to analyze data and generate executive summaries, saving hours of manual report writing.\n\nIntelligent Customer Support: AI-powered chatbots handle 60-80% of support queries, escalating complex issues to human agents with full context.\n\nContent Generation at Scale: Marketing teams are producing blog posts, social media content, and email campaigns 5x faster with AI assistance.\n\nData Analysis and Insights: GPT-4 can analyze unstructured data — emails, call transcripts, reviews — and extract actionable business insights.\n\nThe key to successful GPT-4 integration is starting small, measuring results, and iterating quickly.', 'AI', '9 min read', false, true, '2026-01-15T00:00:00Z');

-- Case Studies
INSERT INTO case_studies (slug, title, industry, client, excerpt, challenge, solution, results, tags, sort_order) VALUES
('techscale-lead-automation', 'TechScale Lead Pipeline Automation', 'SaaS', 'TechScale Inc.', 'Automated their entire lead capture, qualification, and nurture pipeline — reducing manual work from 4 hours daily to zero.', 'TechScale''s sales team spent 4+ hours daily manually processing leads from multiple sources, qualifying them, and entering data into their CRM. Leads were falling through the cracks and response times were too slow.', 'We built a comprehensive n8n automation that captures leads from web forms, LinkedIn, and email, auto-qualifies them using AI scoring, enriches contact data via APIs, and routes qualified leads to sales reps with full context — all in real-time.', '[{"metric":"4h → 0h","label":"daily manual work eliminated"},{"metric":"300%","label":"increase in lead response speed"},{"metric":"45%","label":"improvement in conversion rate"},{"metric":"$120K","label":"annual cost savings"}]'::jsonb, '["n8n","CRM Integration","AI Scoring","Lead Automation"]'::jsonb, 0),
('growthbase-onboarding', 'GrowthBase Client Onboarding', 'Consulting', 'GrowthBase', 'Reduced client onboarding time by 80% with automated document processing, contract generation, and welcome sequences.', 'GrowthBase was manually onboarding each new client — creating contracts, setting up project spaces, sending welcome materials, and scheduling kickoff calls. The process took 3-5 days per client.', 'We implemented an end-to-end onboarding automation: AI-powered contract generation based on proposal data, automatic workspace creation in project management tools, personalized welcome email sequences, and intelligent scheduling integration.', '[{"metric":"80%","label":"reduction in onboarding time"},{"metric":"3-5 days → 4 hours","label":"new onboarding speed"},{"metric":"95%","label":"client satisfaction score"},{"metric":"2x","label":"client capacity increase"}]'::jsonb, '["Document Automation","AI Generation","Onboarding","CRM"]'::jsonb, 1),
('nexus-digital-crm-ai', 'Nexus Digital AI-Powered CRM', 'Digital Marketing', 'Nexus Digital', 'Integrated AI directly into their CRM for intelligent lead scoring, automated follow-ups, and predictive analytics.', 'Nexus Digital''s sales team couldn''t effectively prioritize leads in their CRM. They were spending equal time on all leads regardless of quality, resulting in wasted effort and missed high-value opportunities.', 'We integrated GPT-4 and custom ML models into their CRM pipeline. The AI scores every lead based on 20+ signals, generates personalized follow-up emails, predicts conversion probability, and alerts reps when high-intent leads need immediate attention.', '[{"metric":"60%","label":"increase in sales efficiency"},{"metric":"3.5x","label":"ROI in first quarter"},{"metric":"40%","label":"more deals closed"},{"metric":"50%","label":"reduction in sales cycle"}]'::jsonb, '["AI Integration","GPT-4","CRM","Predictive Analytics"]'::jsonb, 2);
